version: '3'

networks:
    my_net:
        driver: 'bridge'

services:
    database:
        image: "mydb:latest"
        networks:
            - my_net
        restart: always
    api:
        image: "myapi:latest"
        networks:
            - my_net
        ports:
            - 8080:8080
        restart: always
    ui:
        image: "myui:latest"
        networks:
            - my_net
        ports:
            - 3000:3000
        restart: always
